#+OPTIONS: num:nil

* The Crucible

** Background 

*** Puryitans

Temptations were anything that brought joy.

** Characters

*** Betty Parris

*** Reverend Samuel Parris

*** Tituba

*** Abbigail Williams




Motives:

- Do you think she sees a future with John Proctor?
- Does she just want Elizabeth out of the picture?

*** Susanna Wallcot

*** Mrs Ann Putnam

*** Thomas Putnam

*** Mercy Lewis

*** Mary Warren

*** John Proctor

*** Rebecca Nurse

*** Giles Corey

My Wife reads books

*** Reverend John Hale
*** Mrs Elizabeth Proctor
*** Francis Nurse

*** Ezekiel Cheever

Clerk

*** John Williard
*** Danforth

- Drops his logic when his authority is threatened.

*** Proctor

** Themes

** Run Through

*** 64 pg

*** 73 pg

*** ACT THREE

- 80
  - 
- 81
  - We burn a hot fire here; it melts down all

   
* Year of Wonders

NOTE: Incorrect to refer to Salem as within the United States.

** Characters

*** Mompellion
*** Anna
*** Elizabeth
*** Anys Gowdie
*** Mem Gowdie
*** George Viccars
*** Maggie
*** Brand
*** Josiah Bont
*** Aphra Bont
*** Bradfords
*** 

** England 1665-1666

Restoration England

Renaissance technology
Working aquadux
Sewage systems

*** Renaissance

England couldn't get rid of their waste. Therefore diseases would be
common because of the uncleanliness.

In the years coming to the renaissance, human kind had came up
with excellent ways at killing each other.

During the renaissance, their was a revival in art.
- where wars weren't being waged
- bigger questions were being asked.

The prevailing point view of the time was that things are the way they
were. Money was being poored into arts. Time of trying new things.

People were starting to question the ways in which tradition was lead.

The faith of the person who ruled the country was generally what the
country believed in. 

Meeting House = Church.

Spires were like fingers reaching up to heaven.

The puritans believed in the Calvinist philosophy:
- Total depravity :: we are all sinners from birth
- Limited atonement :: Jesus did not die to save us all
- Predestination :: we are born either elect or unregenerate.

From 1542 to 1735 witchcraft in England was a statutory crime punished by death.

Litracy levels were you can only read the Bible.

Imagination was limited to religion and work.


 


* Comparison

** Language of Comparison

- Similarly
- In contrast
- This is juxtaposed by

** Characters

| Yow        | Crucible      |                                                              |
| Danforth   | Mompellion    |                                                              |
| Bradfords  | Parris        | Focused on reputation, survival, money, and their own family |
| Anys & Mem | Rebecca Nurse |                                                              |
| Anna       | Abigail       | Lust and Env                                                 |
|            | Hale          |                                                              |
| Aphra      | Thomas Putnam | Opportunistic and selfish                                    |

*** Opposites

| YOW    | CRUCIBLE |                                                              |
| Elinor | Abigail  | one had a very clear sense of conscience, the other did not. |
|        |          |                                                              |


** Copmparing Communities

Consider:
- The community spirit
- Movtives
- Types of Individuals
- Leadership structures
- Context for each community
- The nature of the crisis affecting each community
- Way the each community understood God
- The role the religion played in day to day life/running of the town

| Simiarities                    |
| <30>                           |
|--------------------------------+
| Both believed in God           |
| The mob were the devil pointers |
| They both engage with superstition |
| Christian commmunites          |
| Religious leaders were de facto leaders for the whole community |
|                                |
|                                |
|                                |
|                                |
|                                |

#+NAME: Differences
| Salem                          | Eyam                           |
| <30>                           | <30>                           |
| Manufactured crisis            | Crisis from nature             |
| People wanted to save themselves | People wanted to save others   |
| Distrust, jealously, competition, conflict, ambitious | Older community, multi-generational, less conflict, everyone has a role |
| Close-minded, unquestioning, suspicious, fearful | More freedom, more creative, seems to more resilient, willing to let things go |
| A messages received from leaders about God was that they were sinful, depraved, beyond redemption, God was mad at them, hell awaited them, the devil tempted them | Mompellion speaks of a God of love. That the trial was not sent as punishment, but as a thing of love |
| Heavily Puritan. Life is therefore dull and devoid of celebration or enjoyment - down religious lines | Is in the middle of a revival in the scientific method, Book of Common Prayer institued - emphasises the majesty and beauty of God and his creation. |



** Symbols 


#+NAME:  YOW
| Symbol             | How it is used |
| Popi Seeds         |                |
| Apples             |                |
| Herbs              |                |
| Fire               |                |
| Earth              |                |
| Water              |                |
| Cross              |                |
| Pulpet             |                |
| Birds              |                |
| Seasons            |                |
| Trees - Growth     |                |
| Naming of Children |                |
| Light              |                |
| Faith              |                |
| God                |                |
| Love               |                |

*** Pg 256


#+NAME: The Crucible
| Symbol          | Explain |
| Poppet          |         |
| God             |         |
| Trees           |         |
| Fire            |         |
| Hell            |         |
| Purity          |         |
| Old Testament   |         |
| Dancing         |         |
| Faith           |         |
| Birds           |         |
| Earth           |         |
| Pulpit          |         |
| Names           |         |
| 10 Commandments |         |



** Birds




* Hurdle Task 1

** Background

- Define what is meant by 'mob mentality'
  - When someone is influenced by their peers to adopt certain behaviours

- Establish an understanding of the different elements of the word
  'setting' (physical, social, historical, religious, geographical)

** Year of Wonders

*** Men and Anys Gowdie are attacked by a mob (pg 87-94)

"There were ten or twelve people in a rough circle"..."At that time,
you see, we all of us believed that God listened to such prayers"

- What does this passage suggest about human impulses in times of
  tragedy? How is the setting in the novel at this point ripe for the
  emergence of a mob?
  - During this time of tragedy, human impulses allowed those who were
    desperate to willingly believe in anything provided the littlest
    of justifications. Due to this gullibility, the society within YOW
    were willing to find closure through whatever they could point
    to. This allowed those with mild suspicions or anger to make
    assumptions such as blaming deaths on witches and ungodly spirits. 
- "Oh yes, the Devil has been here this night! But not in Anys Gowdie!
  Fools! Ignorant wretches!" (pg 94) What does the quote signify about
  setting and human nature in the text?
  - This quote demonstrates the blindsightedness created from the mob
    mentality and the nature it has. Mompellion is able to see this,
    therefore calling the mob fools and ignorant wretches. He renames
    their doings as work of the Devil to expose them to the idea of
    killing the Gowdie sisters for causing the death of their own
    loved ones.

*** Maggie Cantwell is attacked by a mob in Bakewell (pg 124-127)

“Maggie Cantwell came back to us in a handcart"...”This Plague will
make heroes of us all, whether we will or no”

- In this passage, Mompellion calls Brand “the first” hero of the
  plague for saving Maggie from a mob, however Brand is partly
  responsible for the appalling treatment of Aphra towards the end of
  the Plague. What does this suggest about human nature?
  - This suggests that our behaviour is dependent on the circumstance
    and intentions. Brand hesitated to save Maggie but ended up doing
    so when seeing her attacked. This suggests the flight or fight
    mentality when opposed with danger. Human nature allowed Brand to
    come back for her as he said she had took care of him, this
    somewhat motherly relationship could have influenced his
    behavior. It is also an example of loss aversion where Brand was
    willing to risk himself to save Maggie.
  - It suggest when we are scared we do things differently

- What aspect/s of setting helps to contribute to the people of
  Bakewell’s reaction to Maggie?
  - 

*** Aphra is caught by a crowd (pg 242-247)

“What is the meaning of this?” demanded the Rector”….”All the rest of
the way, the child, wide-eyed and silent, cowered by her mother,
clinging to her thigh”

- Anna is close to enacting upon “the urge to hurl spittle on Aphra”
much like the rest of the crowd does, but is stopped by catching sight
of Faith nearby. What might this suggest about the consequences of mob
mentality?
  - Mob mentality is able to influence others despite whether or not
    it is apart of the individuals morals. Anna is able to overcome
    possibly only with a trigger or cue, Faith.
  - 
- The state of Aphra after spending the night in the “lightless,
stinking pit” actually serves to quell any reaction by the crowd. Why?
At this stage of the text, how has the setting changed?
  - This could have been caused by guilt, empathy or an overall
    realisation due to the change in setting. As the plague was near
    and coming to an end, optimism and a lack of impulsive emotions
    (due to exhaustion?) allowed the crowd to come into a normal state
    of mind.

** The Crucible

*** Act One - Rebecca Nurse cautions against inciting group fear (pg 32-50)

“There is prodigious danger in the seeking of loose spirits”…. “I saw
Goody Booth with the devil!”


- Initially, many of the characters try to downplay suggestions of
  group mentality but this quickly changes. Why? How does the setting
  of the play contribute to this?
  - 
- Which characters instigate group mentality and why?
  - Abigail, Tituba, and the other girls as they realised they could
    escape the punishments by shifting the blame on others.

- The Proctors do not engage in mob mentality and, in fact, Miller
  describes John Proctor as ‘not easily led’ (page 27). How does the
  setting of their homestead contribute to the Proctors as outsiders?
  - Due to the information they hold, the Proctors know that the whole
    idea of witches is pretend.
  - 

*** Act Two - Secondary characters are caught up in hysteria (pg 68-75)

"I must do as I'm told"..."I cannot, I cannot, I cannot"

- Cheever and Herrick are two minor characters caught up in the town's
  mob mentality. What are their reactions to the role they play?
  - Cheever and Herrick are powerless compared to that of the
    mob. Therefore there opinions are withheld to themselves so that
    they can avoid the consequences of opposing.
- Mary Warren tells Proctor that she cannot implicate the girls as
  "they'll turn on me" (pg 74). What dangerous elements of mob
  mentality is presented here?
  - This plants fear into those who have 'the truth' refraining them
    from speaking their thoughts. This is very dangerous for the mob
    as it is an enabler for any hysteria the mob can come up with.

*** Act Three - Mary Warren is pressured by the girls to re-join the 'accusers' (pg 101-105)

"You will not! Begone! Begone, I say!"..."I denounce these proceedings"

- This passage is a clear example of the pressures that mob mentality
  can have on an individual. What makes Mary Warren so ripe for
  persuasion?
  - She was threatened with execution therefore she was vulnerable to persuasion.
- Miller has deliberately set this scene in an enclosed space – almost
  claustrophobic. Explain the possible consequences of this setting on
  the choices Mary Warren makes.
  - 




* Prompts

** What do these texts suggest about human behaviour in a crisis?

- How we respond to crisis?
- Types of characters
- Settings
- Depictions of women
- Religion and understandings of God

Year of Wonders is about a crisis caused by nature.
The Crucible is about a crisis caused by humans.

| Year of Wonders  | The Crucible |
|------------------+--------------|
| Forced microcosm |              |

** 'It is individual courage and determination that help bring about change in society'

Danforth and Mompellion are similar.
Elinor, Elizabeth Proctor



How they turned their faith


** "... that the plague was not a thing of God nor devil, but a thing of nature."

Explore the way that the natural world is expressed in Years of
Wonders and The Crucible.

Paragraphs:

- Symbols :: Fire and water
- Supernatural Prescence :: Characters accept that the devil is within
     the town while characters in Salem through hysteria wanted to
     believe it was the devil

Within the texts the presence of the supernatural world is used in
several forms and through acceptance and hysteria is used to instill
purpose or meaning. In Salem, a town of puritans, the supernatural
world is more prevalent in their fear rather than hope. As Arthur
Miller explains in his annotations 'the necessity of the Devil may
become evident as a weapon, a weapon designed and used time and time
again in every age to whip men into a surrender to a particular church
or church-state'. This 'weaponisation' of the supernatural can be seen
in the ways the Putnams saw opportunities in taking Parris's land but
also in the way Abigail manipulates her blame onto others. This
contrasts with Eyam during Mompellion's sermon that 'sealed' their
fates, where instead he suggests that out 'of his great love for us'
the plague becomes an 'opportunity' to demonstrate faith. Here
Mompellion brings the town together through the natural world, while
Abigail tears it apart.





catalyst




** 'Compare how attitudes to faith are transformed by the events of Year of Wonders and The Crucible'

| Eyam | Salem |
|      |       |

* Quotes

** 'a flimsy, tattered thing that is the remnant of [her] own belief'
** 'quail to bring men out of ignorance'


* Words

- microcosm :: a community, place, or situation regarded as
	       encapsulating in miniature the characteristics of
	       something much larger.
- ingenuity :: the quality of being clever, original, and inventive
- quarantine :: 
- foreboding :: like foreshadowing except a bad feeling
- subjugation :: forced control by others
- piety :: Religious devotion and reverence to God
- extremism :: 
- fervour :: 
- bewitched :: 
- flagellation :: 
- redemption :: 
- zealousness :: 
- afflictions :: 
- prodigious :: 
- biblical imagery :: 
- cadence :: 
- cosmology ::
- chastise :: 





* RUBRIC

- Different perspectives of ideas, issues and themes
- Similarites and differences
- Language Analysis
- The way in which...
- 
