#+SETUPFILE: setup.org
#+TITLE: Violent Video Games

* Evidence Study


* Arguments

**

VVG effects on aggression, empathy and pro social behaviour in eastern
and - countries. The evidence strongly suggests that exposure to vvg
is a casual risk factor for increased aggressive behaviour, increased
cognition and decreased empathy and pro social behaiour.

** Columbine Shooting: Live Television Coverage

People relied on the media for information about the shooting. If
people are relying on the media for information they will be subject
to the bias the media is presenting.

** Literature Review

** Betrayal of Violence

1996

Overview of existing research on violent media. 


* Review

** Evidence about VVG

** Arguements about VVG

** Evidence about the effects of media violence.

*** Literature Review

- Context :: Attorney General's Department conducted a review of
             reseach into the effect of VVG. The report looked at a
             range of studies, including experimental research,
             correlation studies, longitudinl research and
             meta-analysis.
- Findings :: the following findings were:
  - There is stronger evidence of short-term VVG effects than of
    long-term effects.
  - The possibility that third variables (like aggressive personality,
    family and peer influence, socio-economic status) are behind the
    effect has not been well explored.
  - Researchers who argue that VVGs cause aggression have not engaged
    with or disproved alternative theories propagated by their
    critics.
  - There is little evidence that violent video games have a greater
    impact than other violent media.
- Conclusion :: research into the effects of VVGs on aggression is
                contested and inconclusive.
